name: Release

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  # goreleaser writes to the releases api
  contents: write

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      run: echo "flags=--snapshot" >> $GITHUB_ENV

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: ^1.21
      id: go

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: git fetch --force --tags

    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release ${{ env.flags }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

